#!/bin/bash

ffmpeg -video_size 1920x1080 -framerate 60 -f x11grab -i :0.0+0.0 -f pulse -ac 2 -ar 48000 -i alsa_output.pci-0000_00_1f.3.analog-stereo.monitor -f pulse -ac 2 -ar 48000 -i alsa_input.pci-0000_00_1f.3.analog-stereo -filter_complex amix=inputs=2 /home/gricowijaya/Videos/Record/PersonalRecording/${1}.mkv
